/// Flutter icons AppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emoHappy = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData downOpen = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData leftOpen = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData rightOpen = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData upOpen = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam);
  static const IconData githubCircled = IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xf0e0, fontFamily: _kFontFam);
  static const IconData linkedin = IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData code = IconData(0xf121, fontFamily: _kFontFam);
  static const IconData youtube = IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData android = IconData(0xf17b, fontFamily: _kFontFam);
  static const IconData codeOpen = IconData(0xf1cb, fontFamily: _kFontFam);
  static const IconData twitch = IconData(0xf1e8, fontFamily: _kFontFam);
  static const IconData medium = IconData(0xf23a, fontFamily: _kFontFam);
}
