/// Flutter icons App
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  App
///      fonts:
///       - asset: fonts/App.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter_web/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData note = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData chat = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData emoHappy = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData downOpen = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData leftOpen = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData rightOpen = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData upOpen = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData code = IconData(0xf121, fontFamily: _kFontFam);
  static const IconData codeopen = IconData(0xf1cb, fontFamily: _kFontFam);
}
