name: wave
description: Widget for displaying waves with custom color, duration, floating and blur effects.
version: 0.2.0
homepage: https://github.com/i-protoss/wave

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.1
  very_good_analysis: 3.0.0
