name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  app:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
          flutter-version: 3.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --dry-run --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze
